version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "slack-bot-chatgpt-python"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-r02my74ly57m"
s3_prefix = "slack-bot-chatgpt-python"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
